name: watchtower-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - nodejs=18
  - npm
  - pip:
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - websockets==12.0
    - prometheus-client==0.19.0
    - requests==2.31.0
    - aiohttp==3.9.1
    - python-multipart==0.0.6
    - python-jose[cryptography]==3.3.0
    - passlib[bcrypt]==1.7.4
    - sqlite-anyio==0.2.0
    - pydantic==2.5.0
    - pydantic-settings==2.1.0
    - langgraph==0.0.33
    - langchain==0.1.0
    - langchain-openai==0.0.5
    - openai==1.6.1
    - chromadb==0.4.15
    - numpy==1.24.3
    - pandas==2.0.3
    - python-dotenv==1.0.0
    - httpx==0.25.2
    - jinja2==3.1.2
    - pytest==7.4.3
    - pytest-asyncio==0.21.1
    - black==23.11.0
    - flake8==6.1.0
    - mypy==1.7.1